### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by flakerimi** [diogoqueiros/ionic-swipe-all#1]
I tried on new app but wont swipe down or up

Ionic Framework: 3.6.0
Ionic App Scripts: 2.1.3
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.2
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Mobile Safari/537.36

**Comment by Michazzz** [comment]
@flakerimi  How to use this plugin?

**Comment by diogoqueiros** [comment]
Hi @flakerimi . I've already fix this, in a few minutes I'll make a new release with other improvements too. As it's done, all the elements with swipe event would swipe in all directions. From now on, it's required to add `swipeAll` property to the element you want to swipe. Feel free to test new release. Thanks for your issue.

@Michazzz I just updated the README. Check it out. Thanks.
