### ISSUE TITLE
Ionic corodva build browser --prod

### ISSUE THREAD

**Issue by SolvingMan** [diogoqueiros/ionic-swipe-all#11]
I have got issuse:
ERROR in Error during template compile of 'IonicSwipeAllModule'
  Function calls are not supported in decorators in 'NgModule'
    'NgModule' calls a function at ../@angular/core/core.ts(194,31).

[ERROR] An error occurred while running subprocess ng.

Please let me know how to fix this.
Thanks

**Comment by diogoqueiros** [comment]
Hi @SolvingMan . Can you please test with the new 1.3.0 version? Thanks.
