### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/Observable'

### ISSUE THREAD

**Issue by marcoinbig** [diogoqueiros/ionic-swipe-all#14]
I try to install the library but after you're code that you write in the Readme.md file I'm getting error Module not found: Error: Can't resolve 'rxjs/Observable' from "mydir\ionic-swipe-all\node_modules\@angular\core\esm5'"

I'm using Ionic 4.
@angular/common : 7.2.2
@angular/core : 7.2.2,

**Comment by diogoqueiros** [comment]
Hi @marcoinbig . It's because of Angular, the v7 uses RxJS v6, which bring many changes including the way imports are made. I need to update dependencies, but in the meantime you can use `rxjs-compat` to get things work.

**Comment by marcoinbig** [comment]
Hi @diogoqueiros thanks for reply. I already implemented a workaround for this... I saw in src folder that you use HammerJS. So, I decided to use that library in the meantime (waiting you're next update).
