### ISSUE TITLE
Is it possible to use lib for any component in Ionic app?

### ISSUE THREAD

**Issue by Michazzz** [diogoqueiros/ionic-swipe-all#3]
Hi, 

I'm trying to use library, that you created, on any page on simple app, but it not working. I have simple page with <ion-header> <ion-content> <ion-footer> and I tried to setup swipeAll for <ion-content>, but if I made that trick, I was unable to find any log in a console with swipe event. 

When I configured library for AppComponent.ts and App.html it works. 

It is possible, in Ionic, use your library to any page in ionic app?

**Comment by diogoqueiros** [comment]
I think it's possible to use on any component/page you want. Did you import IonicSwipeAllModule in your NgModule? Did you declare the component you trying to use in your NgModule? I give you an example.

Let's assume that I want to swipe down an image that's located in MyComponent. In template you can do this:

`<img swipeAll (swipedown)="swipeDown($event)" />`

You should implement the swipeDown function in your MyComponent, to receive the swipe events.

Let's assume that MyComponent belongs to MyModule (in declarations or entryComponents, depending on how you instantiate your component). In your MyModule you need to import the IonicSwipeAllModule:

```javascript
import { IonicSwipeAllModule } from 'ionic-swipe-all';
import { MyComponent } from './my-component';

@NgModule({
  declarations: [MyComponent],
  entryComponents: [MyComponent],
  imports: [IonicSwipeAllModule],
})
export class MyModule {
}
```

This should work.
