### ISSUE TITLE
Error when running 'ionic cordova build ios --prod'

### ISSUE THREAD

**Issue by bendaenen** [diogoqueiros/ionic-swipe-all#4]
Hi @diogoqueiros , 

When trying to build ionic project with flag --prod, an error occurs:

`Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in _app-root_/node_modules/ionic-swipe-all/node_modules/@angular/core/core.d.ts, resolving symbol IonicSwipeAllModule in _app-root_/node_modules/ionic-swipe-all/dist/module.d.ts, resolving symbol IonicSwipeAllModule in _app-root_/node_modules/ionic-swipe-all/dist/module.d.ts`

Tried to figure out why exactly this happens, but so far no idea. Can you have a look at it?

**Comment by bendaenen** [comment]
Maybe related to the fact that I am using angular 4.4.3 in my project and in ionic-swipe-all there is a reference to angular 4.1.3?

**Comment by jlariza** [comment]
Hi,

I am having the same issue running

ionic cordova run android --prod

I am using angular 5.0.0 and ionic-angular@3.9.2

 Thank you

**Comment by diogoqueiros** [comment]
Hi @bendaenen and @jlariza , thanks for the issue. I'll take a look as soon as I can.

**Comment by davidaldan** [comment]
@bendaenen  you solved this problem?

**Comment by bendaenen** [comment]
Well @davidaldan,

I created a custom directive based on this ionic-swipe-all. 
```import { Directive, ElementRef, EventEmitter, OnDestroy, OnInit, Output } from '@angular/core';
import { Gesture } from 'ionic-angular';
declare let Hammer: any;

@Directive({
  selector: '[swipeDown]',
})
export class SwipeDown implements OnInit, OnDestroy {
  @Output() swipeDown = new EventEmitter<any>();

  swipeDownGesture: Gesture;

  constructor(private elem: ElementRef) {}

  ngOnInit() {
    this.swipeDownGesture = new Gesture(this.elem.nativeElement, {
      recognizers: [
        [Hammer.Swipe, {direction: Hammer.DIRECTION_VERTICAL}]
      ]
    });
    this.swipeDownGesture.listen();
    this.swipeDownGesture.on('swipedown', event => {
      this.swipeDown.emit(event);
    })
  }

  ngOnDestroy() {
    this.swipeDownGesture.destroy();
  }

}
```

**Comment by gonself** [comment]
hi @diogoqueiros!
are you going to update the component?
thanks in advanced

**Comment by diogoqueiros** [comment]
Hi @bendaenen, @jlariza, @davidaldan and @gonself, sorry for the delay, only today I got time to look at this. In fact I did reproduce the error reported by @bendaenen. The error itself is a bit confusing, since I don't have any function or lambda references in root module. I think it's a `ng cli` problem which not reporting errors correctly.

I updated Angular and TypeScript to match versions supported by Ionic, and it seems to fix the issue. Now I can run with --prod and --aot flags (tested for Android). Please try to update IonicSwipeAll and keep in touch.

Thanks everyone.

**Comment by APalau82** [comment]
Hi @diogoqueiros. Thank you for your feedback. I updated (even tried remove / reinstall) ionicSwipeAll but still the same issue

`Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing
            the function or lambda with a reference to an exported function (position 194:31 in the original .ts file),
            resolving symbol NgModule in C:/XXX/node_modules/ionic-swipe-all/node_modules/@angular/core/core.d.ts, resolving symbol
            IonicSwipeAllModule in C:/XXX/node_modules/ionic-swipe-all/dist/module.d.ts, resolving symbol IonicSwipeAllModule in
            C:/XXX/node_modules/ionic-swipe-all/dist/module.d.ts`

Is the last version compatible with Angular 5 ?

**My config**

`cli packages: (C:\XXX\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0


local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.5
    npm  : 3.10.10
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro`

Thank you

**Comment by gabrielalberione** [comment]
I have the same problem. Solution? 

 Error during template compile of 'IonicSwipeAllModule' Function calls are not supported in decorators in 'NgModule' 'NgModule' calls a function at @angular\core\core.ts(194,31).

**Comment by diogoqueiros** [comment]
@APalau82 @gabrielalberione I made a few changes in settings to work with `prod` builds. Can you please test again with new 1.3.0 version? Thanks.
